perfana-domain: daniel.perfana.cloud

perfana-url: https://perfana.daniel.perfana.cloud 
perfana-admin-email: admin@perfana.io 
perfana-admin-password: s3cr3t
perfana-api-user: perfana-api-user 
perfana-api-password: s3cr3t 

grafana-url: https://grafana.daniel.perfana.cloud
grafana-admin-email: admin@perfana.io
grafana-admin-password: s3cr3t

mongo-perfana-password: s3cr3t
mongo-root-password: r00ts3cr3t

mysql-password: s3cr3t

jaeger-url: https://jaeger.daniel.perfana.cloud
pyroscope-url: https://pyroscope.daniel.perfana.cloud