repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: influxdata
  url: https://helm.influxdata.com/
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: perfana
  url: https://perfana.github.io/perfana-helm-chart
- name: jaegertracing
  url: https://jaegertracing.github.io/helm-charts
- name: pyroscope-io
  url:  https://pyroscope-io.github.io/helm-chart

helmDefaults:
    wait: true
    waitForJobs: true

releases:
- name: mysql
  chart: bitnami/mysql
  values:
    - mysql/values.yaml

#- name: influxdb
#    chart: influxdata/influxdb
#    values:
#    - values_influxdb.yaml
#
- name: grafana
  chart: grafana/grafana
  needs:
  - mysql
  values:
  - grafana/values.yaml

- name: mongodb
  chart: bitnami/mongodb
  values:
  - mongodb/values.yaml

- name: perfana
  chart: perfana/perfana
  needs:
  - mongodb
  - grafana
  values:
  - perfana/values.yaml

- name: jaeger
  chart: jaegertracing/jaeger
  values:
    - jaeger/values.yaml

- name: pyroscope
  chart: pyroscope-io/pyroscope
  values:
    - pyroscope/values.yaml
