# THIS IS NOT FOR ANY KIND OF USE OTHER THAN AS AN EXAMPLE
# Please use Sealed Secrets or another method for storing Secrets safely and secure.
---
apiVersion: v1
kind: Secret
metadata:
    name: jaeger-cassandra
    namespace: perfana
type: Opaque
stringData:
    password: sup3rs3cr3t