# THIS IS NOT FOR ANY KIND OF USE OTHER THAN AS AN EXAMPLE
# Please use Sealed Secrets or another method for storing Secrets safely and secure.
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: perfana
type: Opaque
stringData:
  admin-password: sup3rs3cr3t
  admin-user: admin@perfana.io

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-database
  namespace: perfana
type: Opaque
stringData:
  url: mysql://grafana:sup3rs3cr3t@mysql:3306/grafana
  provider_config: grafana:sup3rs3cr3t@tcp(mysql:3306)/grafana

---
apiVersion: v1
stringData:
  perfanaApiUser: perfana-api-user
  perfanaApiPassword: sup3rs3cr3t
kind: Secret
metadata:
  name: perfana-api-credentials
  namespace: perfana
type: Opaque