# See default values at https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml
auth:
    database: grafana
    username: grafana
    existingSecret: mysql-credentials
persistence:
    enabled: true
    storageClass: ${STORAGE_CLASS}
    size: 10Gi
resources:
    limits:
        cpu: 2
        memory: 1Gi
    requests:
        cpu: 2
        memory: 1Gi