# See default values at https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml
auth:
    database: grafana
    username: grafana
    existingSecret: mysql-credentials
persistence:
    enabled: true
    storageClass: hcloud-volumes
    size: 10Gi