# THIS IS NOT FOR ANY KIND OF USE OTHER THAN AS AN EXAMPLE
# Please use Sealed Secrets or another method for storing Secrets safely and secure.
---
apiVersion: v1
kind: Secret
metadata:
  name: perfana-admin-credentials
  namespace: perfana
type: Opaque
stringData:
  adminEmail: "admin@perfana.io"
  adminPassword: "sup3rs3cr3t"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-url
  namespace: perfana
type: Opaque
stringData:
  MONGO_URL: "mongodb://perfana:sup3rs3cr3t@mongodb-headless:27017/perfana?authSource=perfana&replicaSet=rs0"
  MONGO_OPLOG_URL: "mongodb://root:sup3rs3cr3t@mongodb-headless:27017/local?authSource=admin&replicaSet=rs0"

---
apiVersion: v1
kind: Secret
metadata:
  name: meteor-settings
  namespace: perfana
type: Opaque
stringData:
    METEOR_SETTINGS: '{
            "autoCreateApplications": true,
            "autoSetBaselineTestRun": true,
            "autoCompareTestRuns": true,
            "adminEmail":"admin@perfana.io",
            "adminPassword":"sup3rs3cr3t",
            "prometheusRetention": "1296000",
            "influxDbRetention": "2592000",
            "elasticSearchRetention": "86400",
            "snapshotExpires": "7776000",
            "perfanaUrl": "${PERFANA_URL}",
            "perfanaCheckUrl": "http://perfana-check:9191",
            "perfanaApiUser": "admin@perfana.io",
            "perfanaApiPassword": "sup3rs3cr3t",
            "helmet": {
              "frameSrc": [
                "https://*.${PERFANA_DOMAIN}"
              ]
            },
            "grafanaInstances": [
              {
                "label": "Demo",
                "clientUrl": "${GRAFANA_URL}",
                "serverUrl": "http://grafana",
                "orgId": "1",
                "snapshotInstance": true,
                "trendsInstance": true,
                "username": "admin@perfana.io",
                "password": "sup3rs3cr3t"
              }
            ],
            "loginExpirationInDays": 1,
            "public": {
                "perfanaUrl": "${PERFANA_URL}",
                "jaegerUrl": "${JAEGER_URL}",
                "pyroscopeUrl": "${PYROSCOPE_URL}",
                "forbidClientAccountCreation": true
            }
        }'

