# THIS IS NOT FOR ANY KIND OF USE OTHER THAN AS AN EXAMPLE
# Please use Sealed Secrets or another method for storing Secrets safely and secure.
---
apiVersion: v1
kind: Secret
metadata:
  name: perfana-admin-credentials
  namespace: perfana
type: Opaque
stringData:
  adminEmail: "{{ .Values.grafana-admin-email }}"
  adminPassword: "{{ .Values.grafana-admin-password }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-url
  namespace: perfana
type: Opaque
stringData:
  MONGO_URL: "mongodb://perfana:{{ .Values.mongo-perfana-password }}@mongodb-headless:27017/perfana?authSource=perfana&replicaSet=rs0"
  MONGO_OPLOG_URL: "mongodb://root:{{ .Values.mongo-root-password }}@mongodb-headless:27017/local?authSource=admin&replicaSet=rs0"

---
---
apiVersion: v1
kind: Secret
metadata:
  name: meteor-settings
  namespace: perfana
type: Opaque
stringData:
    METEOR_SETTINGS: '{
            "autoCreateApplications": true,
            "autoSetBaselineTestRun": true,
            "autoCompareTestRuns": true,
            "adminEmail":"$perfana-admin-email",
            "adminPassword":"$perfana-admin-password",
            "prometheusRetention": "1296000",
            "influxDbRetention": "2592000",
            "elasticSearchRetention": "86400",
            "snapshotExpires": "7776000",
            "perfanaUrl": "{{ .Values.perfana-url }}",
            "perfanaCheckUrl": "http://perfana-check:9191",
            "perfanaApiUser": "{{ .Values.perfana-admin-user }}",
            "perfanaApiPassword": "{{ .Values.perfana-admin-password }}",
            "helmet": {
              "frameSrc": [
                "https://*.{{ .Values.perfana-domain }}"
              ]
            },
            "grafanaInstances": [
              {
                "label": "Demo",
                "clientUrl": "{{ .Values.grafana-url }}",
                "serverUrl": "http://grafana",
                "orgId": "1",
                "snapshotInstance": true,
                "trendsInstance": true,
                "username": "{{ .Values.grafana-admin-email }}",
                "password": "{{ .Values.grafana-admin-password }}"
              }
            ],
            "loginExpirationInDays": 1,
            "public": {
                "perfanaUrl": "{{ .Values.perfana-url }}",
                "jaegerUrl": "{{ .Values.jaeger-url }}",
                "pyroscopeUrl": "{{ .Values.pyroscope-url }}",
                "forbidClientAccountCreation": true
            }
        }'

